apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: 
  - host: app.jmoncada.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crud-service
            port:
              number: 80